### ISSUE TITLE
The device does not support the specified langid

### ISSUE THREAD

**Issue by CampbellWray** [andrewdodd/pyCCSniffer#4]
When running `sudo python pyCCSniffer.py` with `Python 2.7.9` The following exception occurs:

```
Traceback (most recent call last):
  File "pyCCSniffer.py", line 520, in <module>
    snifferDev = CC2531EMK(handlerDispatcher, args.channel)
  File "pyCCSniffer.py", line 293, in __init__
    self.name = usb.util.get_string(self.dev, 256, 2) # get name from USB descriptor
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 318, in get_string
    raise ValueError("The device does not support the specified langid")
ValueError: The device does not support the specified langid
```

It seems to be related to `pyusb`, but I have no real experience with python so I don't really know.

I have the following python modules installed:

```
RPi.GPIO==0.6.3
argparse==1.2.1
chardet==2.3.0
colorama==0.3.2
future==0.16.0
html5lib==0.999
ndg-httpsclient==0.3.2
pyOpenSSL==0.13.1
pyasn1==0.1.7
python-apt==0.9.3.12
pyusb==1.0.0
requests==2.4.3
six==1.8.0
urllib3==1.9.1
wheel==0.24.0
wsgiref==0.1.2
```

For `pyusb` I have installed `libusb`:

```
libusb-0.1-4/stable,now 2:0.1.12-25 armhf [installed]
libusb-1.0-0/stable,now 2:1.0.19-1 armhf [installed]
libusb-1.0-0-dbg/stable,now 2:1.0.19-1 armhf [installed]
libusb-1.0-0-dev/stable,now 2:1.0.19-1 armhf [installed]
libusb-1.0-doc/stable,now 2:1.0.19-1 all [installed]
```

**Comment by CampbellWray** [comment]
I have managed to get it working by changing the following:
`self.name = usb.util.get_string(self.dev, 256, 1033) # get name from USB descriptor`
Perhaps there are multiple versions of the CC2531 with varying langids

Hopefully this can help someone else in the future

**Comment by andrewdodd** [comment]
Hi,

Unfortunately I don't have any CC2531 sniffers anymore, so I can't really help! It looks like you've solved your own issue. Interestingly, it looks like you are running this in an Raspberry Pi (or something like it), I wonder if that has anything to do with it.

Thanks for the update.

**Comment by CampbellWray** [comment]
Thank you for looking into this Andrew, it is much appreciated.

You have a good eye this particular set of dumps was on a Raspberry Pi, but the same issue existed on my Ubuntu machine.
