### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by smdjeff** [andrewdodd/pyCCSniffer#5]
What firmware is supposed to be loaded?

**Comment by andrewdodd** [comment]
Hi @smdjeff ,

Unfortunately I don't get to work with 802.15.4 any more and so I haven't really used this library since around 2015. I had a quick look [here](http://www.ti.com/tool/cc2531emk#technicaldocuments) but couldn't see a listing of USB sniffer dongle firmware, so I can't really point you to anything.

Is there a particular issue you are having?

**Comment by smdjeff** [comment]
I was psyched to find pyCCSniffer since I'm working on Mac and all of the
TI tools are windows based.  It appears you're searching for vendor =
0x0451 and product = 0x16ae what hardware and .hex image are you expecting
to be loaded on the USB stick?

This is what I'm seeing:

Jeffs-iMac:pyCCSniffer-master jmathews$ ./pyCCSniffer.py
Commands:
c: Print current RF Channel
h,?: Print this message
[11,26]: Change RF channel
s: Start/stop the packet capture
d: Toggle frame dissector
a*: Set an annotation (write "a" to remove it)
q: Quit
Traceback (most recent call last):
  File "./pyCCSniffer.py", line 520, in <module>
    snifferDev = CC2531EMK(handlerDispatcher, args.channel)
  File "./pyCCSniffer.py", line 290, in __init__
    raise IOError("Device not found")
IOError: Device not found

ioreg -p IOUSB -l -w 0
...
 +-o CC2531 USB CDC@14600000  <class AppleUSBDevice, id 0x100001a8d,
registered, matched, active, busy 0 (6 ms), retain 13>
        {
          "sessionID" = 58732862009409
          "iManufacturer" = 1
          "bNumConfigurations" = 1
          "idProduct" = 5800
          "bcdDevice" = 9
          "Bus Power Available" = 250
          "USB Address" = 29
          "bMaxPacketSize0" = 32
          "iProduct" = 2
          "iSerialNumber" = 3
          "bDeviceClass" = 2
          "Built-In" = No
          "locationID" = 341835776
          "bDeviceSubClass" = 0
          "bcdUSB" = 512
          "USB Product Name" = "CC2531 USB CDC"
          "PortNum" = 6
          "non-removable" = "no"
          "IOCFPlugInTypes" =
{"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
          "bDeviceProtocol" = 0
          "IOUserClientClass" = "IOUSBDeviceUserClientV2"
          "IOPowerManagement" =
{"DevicePowerState"=0,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
          "kUSBCurrentConfiguration" = 1
          "Device Speed" = 1
          "USB Vendor Name" = "Texas Instruments"
          "idVendor" = 1105
          "IOGeneralInterest" = "IOCommand is not serializable"
          "USB Serial Number" = "001"
          "IOClassNameOverride" = "IOUSBDevice"
        }

**Comment by andrewdodd** [comment]
Hi Jeff,

I have had a look into this (I went digging in my box of stuff to find my old sniffer dongle!).

I'm not really sure what is going on, but perhaps you have not loaded the sniffer firmware on to your dongle? This is discussed in this [forum thread](https://e2e.ti.com/support/wireless_connectivity/low_power_rf_tools/f/155/t/48529?CC2531-USB-Dongle-not-detected-by-Packet-sniffer-). Have you had a read of that?

When I run  ` > ioreg -p IOUSB -l -w 0` with my dongle plugged in I get this:

```
    +-o CC2531 USB Dongle@14100000  <class AppleUSBDevice, id 0x1000032ab, registered, matched, active, busy 0 (904 ms), retain 20>
        {
          "sessionID" = 100416019357668
          "iManufacturer" = 1
          "bNumConfigurations" = 1
          "idProduct" = 5806
          "bcdDevice" = 21331
          "Bus Power Available" = 250
          "USB Address" = 9
          "bMaxPacketSize0" = 32
          "iProduct" = 2
          "iSerialNumber" = 0
          "bDeviceClass" = 0
          "Built-In" = No
          "locationID" = 336592896
          "bDeviceSubClass" = 0
          "bcdUSB" = 512
          "USB Product Name" = "CC2531 USB Dongle"
          "PortNum" = 1
          "non-removable" = "no"
          "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
          "bDeviceProtocol" = 0
          "IOUserClientClass" = "IOUSBDeviceUserClientV2"
          "IOPowerManagement" = {"DevicePowerState"=0,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
          "kUSBCurrentConfiguration" = 1
          "Device Speed" = 1
          "USB Vendor Name" = "Texas Instruments"
          "idVendor" = 1105
          "IOGeneralInterest" = "IOCommand is not serializable"
          "IOClassNameOverride" = "IOUSBDevice"
        }
```

Does your sniffer work with the Texas Instruments windows GUI? I'd suggest getting it working with that first.

**Comment by andrewdodd** [comment]
I'm going to assume you got it working!

**Comment by smdjeff** [comment]
Yes thank you.
